# === Windows: 开发环境交互式一键配置 ===
# 首次运行：一问一答引导式，保存配置后自动安装。
# 再次运行：检测到已有配置跳过问答。
#
# 管理员身份推荐（安装 msys2 时需要写入权限）。
# ============================================================

# Source modules
. "$PSScriptRoot\check.ps1"
. "$PSScriptRoot\download.ps1"
. "$PSScriptRoot\install.ps1"
. "$PSScriptRoot\config.ps1"
. "$PSScriptRoot\verify.ps1"

# Profile path (mirror PopOS style)
$ProfileDir = "$HOME\.config\envbat"
$ProfileFile = "$ProfileDir\profile.ps1"

# ---- Prompt helpers ----
function Ask-YesNo {
    param([string]$prompt, [string]$default = "Y")
    while ($true) {
        $hint = if ($default -eq "Y") { "Y/n" } else { "y/N" }
        $answer = Read-Host "$prompt ($hint)"
        if ($answer -eq "") { $answer = $default }
        switch -regex ($answer) {
            "^[Yy]" { return $true }
            "^[Nn]" { return $false }
            default { Write-Host "  请输入 y 或 n" }
        }
    }
}

function Ask-Input {
    param([string]$prompt, [string]$default, [string]$varName)
    $hint = if ($default) { " (默认: $default)" } else { "" }
    $input = Read-Host "$prompt$hint"
    if ($input -eq "") { $input = $default }
    Set-Variable -Name $varName -Value $input -Scope 1
}

# ---- Load / Save profile ----
function Load-Profile {
    if (Test-Path $ProfileFile) {
        . $ProfileFile
        Write-Host "  [OK] 已加载配置: $ProfileFile"
        return $true
    }
    return $false
}

function Save-Profile {
    if (-not (Test-Path $ProfileDir)) { New-Item -Path $ProfileDir -ItemType Directory -Force | Out-Null }
    @"
# === envbat Windows profile ===
# Generated by setup.ps1 $(Get-Date -Format 'yyyy-MM-dd')
# Delete this file to re-run interactive setup.

`$global:INSTALL_BASE = "$INSTALL_BASE"
`$global:INSTALL_GO = `$$INSTALL_GO
`$global:INSTALL_JAVA = `$$INSTALL_JAVA
`$global:INSTALL_PYTHON = `$$INSTALL_PYTHON
`$global:INSTALL_MSYS2 = `$$INSTALL_MSYS2
"@ | Out-File -FilePath $ProfileFile -Encoding utf8
    Write-Host "  [OK] 配置已保存: $ProfileFile"
}

# ---- Interactive questions ----
function Ask-Questions {
    Write-Host "`n== 安装基础路径 =="
    $defaultBase = "$HOME\local\envs"
    Ask-Input -prompt "请输入安装基础目录" -default $defaultBase -varName "inputBase"
    $script:INSTALL_BASE = $inputBase
    Write-Host "  安装基础: $INSTALL_BASE"

    Write-Host "`n== 开发语言 =="
    $script:INSTALL_GO     = if (Ask-YesNo -prompt "安装 Go 语言?"                 -default "Y") { $true } else { $false }
    $script:INSTALL_JAVA   = if (Ask-YesNo -prompt "安装 Java JDK 21?"              -default "Y") { $true } else { $false }
    $script:INSTALL_PYTHON = if (Ask-YesNo -prompt "安装 Python (embeddable + uv)?" -default "Y") { $true } else { $false }
    $script:INSTALL_MSYS2  = if (Ask-YesNo -prompt "安装 MSYS2 (C/C++ 编译环境)?"   -default "Y") { $true } else { $false }
}

# ============================================================
# Main
# ============================================================
Write-Host @"

################################################
#  envbat Windows — 交互式环境配置               #
################################################
"@

# Admin check
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Warning "  未以管理员身份运行，MSYS2 安装可能需要权限"
    if (-not (Ask-YesNo -prompt "是否继续?" -default "N")) { exit }
}

# Profile
if (Load-Profile) {
    if (-not (Ask-YesNo -prompt "检测到已有配置，是否重新配置?" -default "N")) {
        Write-Host "  使用现有配置继续安装"
    } else {
        Ask-Questions
        Save-Profile
    }
} else {
    Ask-Questions
    Save-Profile
}

# Choices hashtable for passing to modules
$choices = @{
    "go"     = $INSTALL_GO
    "java"   = $INSTALL_JAVA
    "python" = $INSTALL_PYTHON
    "msys2"  = $INSTALL_MSYS2
}

# Check existing
Write-Host "`n--- 检查已有安装 ---"
$languages = @()
if ($INSTALL_GO)     { $languages += "Golang" }
if ($INSTALL_JAVA)   { $languages += "Java" }
if ($INSTALL_PYTHON) { $languages += "Python" }
if ($INSTALL_MSYS2)  { $languages += "C"; $languages += "C++" }
if ($languages.Count -gt 0) {
    $existing = Check-AllInstallations -programmingLanguages $languages
    $existing | ForEach-Object { Write-Host "  $_" }
}

# Download (skip existing cached files)
Write-Host "`n--- 下载安装包 ---"
$packageFiles = Download-Packages -installPath $INSTALL_BASE -choices $choices -skipExisting

# Install
Write-Host "`n--- 安装 ---"
Install-All -installBase $INSTALL_BASE -choices $choices -packageFiles $packageFiles

# PATH configuration
Write-Host "`n--- 配置环境变量 ---"
Add-ToUserPath -installBase $INSTALL_BASE -choices $choices
Set-JavaHome -installBase $INSTALL_BASE
Write-Host "  [HINT] 需要重新打开终端或重启后 PATH 才会完全生效"

# Verify
Verify-Installations -installBase $INSTALL_BASE -choices $choices

# Done
Write-Host @"

========================================
 ✅ Windows 环境配置完成！

  重新打开终端后，工具将可用。
  使用 'uv venv' 创建 Python 虚拟环境。
========================================
"@
