#!/usr/bin/env bash
# === Profile Persistence ===
# Stores interactive answers so re-runs skip questioning.
# Location: ~/.config/envbat/profile.sh
#
# Usage (source this file):
#   popos_load_profile   → source profile if exists, returns 0 or 1
#   popos_save_profile   → write current vars to profile
#   popos_clean_old_bashrc → remove legacy env vars from .bashrc

PROFILE_DIR="$HOME/.config/envbat"
PROFILE_FILE="$PROFILE_DIR/profile.sh"

# Variables that get persisted (set by interactive.sh questions)
# These are populated by setup.sh before calling popos_save_profile:
#   INSTALL_BASE        — /data or custom
#   INSTALL_GO          — true/false
#   INSTALL_NVM_NODE    — true/false
#   INSTALL_PYENV       — true/false
#   INSTALL_RUSTUP      — true/false
#   INSTALL_JAVA        — version or "skip"
#   INSTALL_NEOVIM      — true/false
#   INSTALL_DOCKER      — true/false
#   INSTALL_OHMYZSH     — true/false
#   INSTALL_SSH         — generate/restore/skip
#   INSTALL_EXTRA_TOOLS — true/false
#   GIT_USER_NAME       — string
#   GIT_USER_EMAIL      — string
#   GO_VERSION          — e.g. "1.23"
#   JAVA_VERSION        — e.g. "21"

popos_load_profile() {
    if [ -f "$PROFILE_FILE" ]; then
        # shellcheck source=/dev/null
        source "$PROFILE_FILE"
        popos_profile_defaults
        ok "已加载配置: $PROFILE_FILE"
        return 0
    fi
    return 1
}

popos_profile_defaults() {
    INSTALL_GO="${INSTALL_GO:-true}"
    INSTALL_NVM_NODE="${INSTALL_NVM_NODE:-true}"
    INSTALL_PYENV="${INSTALL_PYENV:-true}"
    INSTALL_RUSTUP="${INSTALL_RUSTUP:-true}"
    INSTALL_JAVA="${INSTALL_JAVA:-21}"
    INSTALL_NEOVIM="${INSTALL_NEOVIM:-true}"
    INSTALL_DOCKER="${INSTALL_DOCKER:-true}"
    INSTALL_OHMYZSH="${INSTALL_OHMYZSH:-true}"
    INSTALL_SSH="${INSTALL_SSH:-generate}"
    INSTALL_EXTRA_TOOLS="${INSTALL_EXTRA_TOOLS:-true}"
    INSTALL_UFW="${INSTALL_UFW:-true}"
    INSTALL_FAIL2BAN="${INSTALL_FAIL2BAN:-true}"
    INSTALL_AUTO_UPDATES="${INSTALL_AUTO_UPDATES:-true}"
    INSTALL_CHINESE="${INSTALL_CHINESE:-true}"
    INSTALL_CHROME="${INSTALL_CHROME:-true}"
}

popos_save_profile() {
    popos_profile_defaults
    mkdir -p "$PROFILE_DIR"
    cat > "$PROFILE_FILE" << PROFILEEOF
# === envbat profile ===
# Generated by setup.sh $(date +%Y-%m-%d)
# Delete this file to re-run interactive setup.

INSTALL_BASE="${INSTALL_BASE:-/data}"

# Derived environment variables
export DATA_HOME="${INSTALL_BASE}"
export CODE_HOME="${INSTALL_BASE}/workspace/github"
export TOOLS_HOME="${INSTALL_BASE}/tools"
export HF_HOME="${INSTALL_BASE}/models/huggingface"
export CARGO_HOME="${INSTALL_BASE}/tools/cargo"
export XDG_DATA_HOME="${INSTALL_BASE}/temp/xdg-data"
export XDG_CACHE_HOME="${INSTALL_BASE}/temp/xdg-cache"
export TMPDIR="${INSTALL_BASE}/temp"
# Extend PATH with tools/bin
if [ -d "\${TOOLS_HOME}/bin" ]; then
    export PATH="\${TOOLS_HOME}/bin:\${PATH}"
fi

INSTALL_GO="${INSTALL_GO:-true}"
INSTALL_NVM_NODE="${INSTALL_NVM_NODE:-true}"
INSTALL_PYENV="${INSTALL_PYENV:-true}"
INSTALL_RUSTUP="${INSTALL_RUSTUP:-true}"
INSTALL_JAVA="${INSTALL_JAVA:-21}"
INSTALL_NEOVIM="${INSTALL_NEOVIM:-true}"
INSTALL_DOCKER="${INSTALL_DOCKER:-true}"
INSTALL_OHMYZSH="${INSTALL_OHMYZSH:-true}"
INSTALL_SSH="${INSTALL_SSH:-generate}"
INSTALL_EXTRA_TOOLS="${INSTALL_EXTRA_TOOLS:-true}"
GIT_USER_NAME="${GIT_USER_NAME:-}"
GIT_USER_EMAIL="${GIT_USER_EMAIL:-}"
GO_VERSION="${GO_VERSION:-}"
JAVA_VERSION="${JAVA_VERSION:-21}"
INSTALL_UFW="${INSTALL_UFW:-true}"
INSTALL_FAIL2BAN="${INSTALL_FAIL2BAN:-true}"
INSTALL_AUTO_UPDATES="${INSTALL_AUTO_UPDATES:-true}"
INSTALL_CHINESE="${INSTALL_CHINESE:-true}"
INSTALL_CHROME="${INSTALL_CHROME:-true}"

# nvm
export NVM_DIR="${INSTALL_BASE}/tools/nvm"
[ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"

# pyenv
export PYENV_ROOT="${INSTALL_BASE}/tools/pyenv"
export PATH="\$PYENV_ROOT/bin:\$PATH"
if command -v pyenv &>/dev/null; then
    eval "\$(pyenv init -)"
fi

# Rust
export RUSTUP_HOME="${INSTALL_BASE}/tools/rustup"
export PATH="\${CARGO_HOME}/bin:\$PATH"
PROFILEEOF
    ok "配置已保存: $PROFILE_FILE"

    # Auto-source in .bashrc
    local guard="# === envbat ==="
    local source_line='if [ -f "$HOME/.config/envbat/profile.sh" ]; then source "$HOME/.config/envbat/profile.sh"; fi'
    if ! grep -qF ".config/envbat/profile.sh" "$HOME/.bashrc" 2>/dev/null; then
        {
            echo ""
            echo "$guard"
            echo "$source_line"
        } >> "$HOME/.bashrc"
        ok ".bashrc 已添加 envbat 加载"
    fi
    # Auto-source in .zshrc (if exists or will exist after oh-my-zsh install)
    if [ ! -f "$HOME/.zshrc" ] || ! grep -qF ".config/envbat/profile.sh" "$HOME/.zshrc" 2>/dev/null; then
        {
            echo ""
            echo "$guard"
            echo "$source_line"
        } >> "$HOME/.zshrc" 2>/dev/null || true
        [ -f "$HOME/.zshrc" ] && ok ".zshrc 已添加 envbat 加载"
    fi
}

popos_clean_old_bashrc() {
    local bashrc="$HOME/.bashrc"
    local guard="# === PopOS Environment ==="
    if grep -qF "$guard" "$bashrc" 2>/dev/null; then
        # Remove from the guard line to the blank line after env block
        sed -i "/$guard/,/^$/d" "$bashrc"
        ok "已清理 .bashrc 中的旧环境变量段"
    fi
}
