#!/usr/bin/env bash
# === Shell Setup: oh-my-zsh + Powerlevel10k + Plugins ===

_popos_backup_path() {
    local target="$1"
    local backup
    backup="${target}.envbat-incomplete-$(date +%Y%m%d%H%M%S)"
    if [ -e "$backup" ]; then
        backup="${backup}.$$"
    fi
    printf '%s\n' "$backup"
}

_popos_install_ohmyzsh_repo() {
    local target="$HOME/.oh-my-zsh"
    local marker="$target/oh-my-zsh.sh"
    if [ -f "$marker" ]; then
        echo "  [SKIP] oh-my-zsh 已安装"
        return 0
    fi

    local temp_dir staged backup=""
    if ! temp_dir=$(mktemp -d "${TMPDIR:-/tmp}/envbat-ohmyzsh.XXXXXX"); then
        fail "无法创建 oh-my-zsh 临时目录"
        return 1
    fi
    staged="$temp_dir/oh-my-zsh"

    if ! git clone --depth 1 https://github.com/ohmyzsh/ohmyzsh.git "$staged"; then
        rm -rf -- "$temp_dir"
        fail "oh-my-zsh 下载失败，请检查 GitHub 网络连通"
        return 1
    fi
    if [ ! -f "$staged/oh-my-zsh.sh" ]; then
        rm -rf -- "$temp_dir"
        fail "oh-my-zsh 下载不完整"
        return 1
    fi

    if [ -d "$target/custom" ]; then
        if ! mkdir -p "$staged/custom" || ! cp -a "$target/custom/." "$staged/custom/"; then
            rm -rf -- "$temp_dir"
            fail "保留现有 oh-my-zsh custom 失败，原目录未修改"
            return 1
        fi
    fi

    if [ -e "$target" ] || [ -L "$target" ]; then
        backup=$(_popos_backup_path "$target")
        if ! mv "$target" "$backup"; then
            rm -rf -- "$temp_dir"
            fail "无法备份不完整的 oh-my-zsh 目录"
            return 1
        fi
    fi

    if ! mv "$staged" "$target"; then
        if [ -n "$backup" ]; then
            mv "$backup" "$target" || warn "oh-my-zsh 原目录自动回滚失败: $backup"
        fi
        rm -rf -- "$temp_dir"
        fail "oh-my-zsh 安装目录替换失败"
        return 1
    fi
    rm -rf -- "$temp_dir"

    if [ -n "$backup" ]; then
        warn "不完整的 oh-my-zsh 已保留在: $backup"
    fi
    ok "oh-my-zsh 已安装"
}

_popos_install_git_component() {
    local label="$1" repo="$2" target="$3" marker="$4"
    if [ -f "$target/$marker" ]; then
        echo "  [SKIP] $label 已安装"
        return 0
    fi

    local backup=""
    if [ -e "$target" ] || [ -L "$target" ]; then
        backup=$(_popos_backup_path "$target")
        if ! mv "$target" "$backup"; then
            fail "无法备份不完整的 $label 目录"
            return 1
        fi
    fi

    if ! mkdir -p "$(dirname "$target")"; then
        [ -n "$backup" ] && mv "$backup" "$target"
        fail "无法创建 $label 安装目录"
        return 1
    fi

    if git clone --depth 1 "$repo" "$target" && [ -f "$target/$marker" ]; then
        if [ -n "$backup" ]; then
            warn "$label 的不完整目录已保留在: $backup"
        fi
        ok "$label 已安装"
        return 0
    fi

    rm -rf -- "$target"
    if [ -n "$backup" ] && ! mv "$backup" "$target"; then
        warn "$label 原目录自动回滚失败: $backup"
    fi
    fail "$label 下载失败或安装不完整，请检查 GitHub 网络连通"
    return 1
}

_popos_setup_p10k_config() {
    local p10k_cfg="$HOME/.p10k.zsh"
    if [ -f "$p10k_cfg" ]; then
        echo "  [SKIP] .p10k.zsh 已存在"
        return 0
    fi

    echo "  生成 .p10k.zsh (Nerd Font 图标模式)..."
    if ! cat > "$p10k_cfg" <<'P10KEOF'
# Generated by envbat setup. Edit or run `p10k configure` to customize.

typeset -g POWERLEVEL9K_MODE=nerdfont-complete

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs prompt_char)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time)

typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE="%n@%m"
typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_CONTENT_VISUAL_IDENTIFIER_EXPANSION=

typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=40

typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS=true
typeset -g POWERLEVEL9K_STATUS_VERBOSE=false

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0

typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off

typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=1
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=0
typeset -g POWERLEVEL9K_DIR_HOME_BACKGROUND=4
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND=0
typeset -g POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=4
typeset -g POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=0

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=2
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=1
P10KEOF
    then
        fail ".p10k.zsh 写入失败"
        return 1
    fi

    ok ".p10k.zsh 已生成"
    echo "  [HINT] 运行 p10k configure 可交互式自定义样式"
}

_popos_configure_zshrc() {
    local zshrc="$HOME/.zshrc"
    local temp_file
    if ! touch "$zshrc"; then
        fail "无法创建或写入 .zshrc"
        return 1
    fi
    if ! temp_file=$(mktemp "${zshrc}.envbat.XXXXXX"); then
        fail "无法创建 .zshrc 临时文件"
        return 1
    fi

    if ! awk '
        $0 == "# === envbat zsh ===" { next }
        $0 == "# === end envbat zsh ===" { next }
        /^[[:space:]]*(export[[:space:]]+)?ZSH=/ { next }
        /^[[:space:]]*ZSH_THEME=/ { next }
        /^[[:space:]]*plugins=/ { next }
        /^[[:space:]]*(source|\.)[[:space:]]+.*oh-my-zsh\.sh/ { next }
        $0 == "[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh" { next }
        $0 == "[[ -f \"$HOME/.p10k.zsh\" ]] && source \"$HOME/.p10k.zsh\"" { next }
        { lines[++count] = $0 }
        END {
            while (count > 0 && lines[count] ~ /^[[:space:]]*$/) {
                count--
            }
            for (i = 1; i <= count; i++) {
                print lines[i]
            }
        }
    ' "$zshrc" > "$temp_file"; then
        rm -f -- "$temp_file"
        fail ".zshrc 清理旧配置失败"
        return 1
    fi

    if ! cat >> "$temp_file" <<'ZSHRCEOF'

# === envbat zsh ===
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting fzf)
source "$ZSH/oh-my-zsh.sh"
[[ -f "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"
# === end envbat zsh ===
ZSHRCEOF
    then
        rm -f -- "$temp_file"
        fail ".zshrc 新配置写入失败"
        return 1
    fi

    if ! mv "$temp_file" "$zshrc"; then
        rm -f -- "$temp_file"
        fail ".zshrc 更新失败"
        return 1
    fi
    ok ".zshrc 已配置 oh-my-zsh 和 Powerlevel10k"
}

popos_install_ohmyzsh() {
    echo ">>> 安装 oh-my-zsh <<<"
    if ! command -v zsh &>/dev/null; then
        echo "  安装 zsh..."
        if ! sudo apt-get install -y -qq zsh; then
            fail "zsh 安装失败"
            return 1
        fi
    fi

    local zsh_bin
    zsh_bin="$(command -v zsh || true)"
    if [ -z "$zsh_bin" ]; then
        fail "zsh 未安装，跳过 oh-my-zsh 配置"
        return 1
    fi

    _popos_install_ohmyzsh_repo || return 1

    echo ">>> 安装 Powerlevel10k <<<"
    local p10k_dir="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
    _popos_install_git_component \
        "Powerlevel10k" \
        "https://github.com/romkatv/powerlevel10k.git" \
        "$p10k_dir" \
        "powerlevel10k.zsh-theme" || return 1

    echo ">>> 安装 Zsh 插件 <<<"
    local custom_dir="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins"
    _popos_install_git_component \
        "zsh-autosuggestions" \
        "https://github.com/zsh-users/zsh-autosuggestions" \
        "$custom_dir/zsh-autosuggestions" \
        "zsh-autosuggestions.plugin.zsh" || return 1
    _popos_install_git_component \
        "zsh-syntax-highlighting" \
        "https://github.com/zsh-users/zsh-syntax-highlighting" \
        "$custom_dir/zsh-syntax-highlighting" \
        "zsh-syntax-highlighting.plugin.zsh" || return 1

    _popos_setup_p10k_config || return 1
    _popos_configure_zshrc || return 1

    if ! grep -qxF "$zsh_bin" /etc/shells 2>/dev/null; then
        if ! echo "$zsh_bin" | sudo tee -a /etc/shells >/dev/null; then
            fail "无法将 zsh 加入 /etc/shells"
            return 1
        fi
    fi

    local login_shell
    login_shell="$(getent passwd "$USER" 2>/dev/null | cut -d: -f7 || true)"
    if [ "$login_shell" != "$zsh_bin" ]; then
        if sudo chsh -s "$zsh_bin" "$USER"; then
            ok "默认 shell 已切换为 zsh (重新登录生效)"
        else
            warn "chsh 失败，请手动运行: sudo chsh -s $zsh_bin $USER"
            return 1
        fi
    else
        echo "  [OK] 默认 shell 已是 zsh"
    fi
}
